- Bail out on errors. - Do not, do not set PWMODe for the second @. ;-)
git-svn-id: svn+ssh://svn.berlios.de/svnroot/repos/freenx/trunk@597 80778403-ebee-0310-8e0a-e86a689f3fff

diff --git a/freenx-utils/nxpublickey/nxssh-wrapper b/freenx-utils/nxpublickey/nxssh-wrapper
--- a/freenx-utils/nxpublickey/nxssh-wrapper
+++ b/freenx-utils/nxpublickey/nxssh-wrapper
@@ -43,7 +43,6 @@ NX> 202 Authenticating user: nx
 NX> 208 Using auth method: publickey
 EOF
 	
-
 	echo "HELLO NXSERVER - Version 3.2.0 OS (GPL Edition)"	
 
 	# Login stage
@@ -124,8 +123,6 @@ EOF
 	
 	case "$USER2" in 
 		*"@"*)
-			# do not use password for authentication
-			PWMODE=0
 			MODE=$(echo $USER2 | cut -d'@' -f2)
 			[ "$MODE" = "U" ] && NXSERVER_SUID=/bin/false
 			[ "$MODE" = "S" ] && NXSERVER_USERMODE=/bin/falsedoesnotexist
@@ -137,16 +134,20 @@ EOF
 
 	if [ "$PWMODE" != "1" ]
 	then 
-		$(dirname $0)/nxssh.orig -nxstdinpass "$USER2@$CONN" -x -2 -B -o "NumberOfPasswordPrompts 1" sh -c "'$REMOTE_COMMAND'" || {
-                echo "NX> 404 ERROR: wrong password or login."
-                echo "NX> 999 Bye"
-                exit 1
-             }
+		$(dirname $0)/nxssh.orig -nxstdinpass "$USER2@$CONN" -x -2 -B -o "NumberOfPasswordPrompts 1" sh -c "'$REMOTE_COMMAND'" 
 	else
 		export SSH_ASKPASS=/usr/bin/ssh-askpass
 
-		exec $(dirname $0)/nxssh.orig "$USER2@$CONN" -x -2 -B sh -c "'$REMOTE_COMMAND'"
+		$(dirname $0)/nxssh.orig "$USER2@$CONN" -x -2 -B sh -c "'$REMOTE_COMMAND'"
 	fi
+
+	if [ $? -ne 0 ]
+	then
+		echo "NX> 404 ERROR: wrong password or login."
+        	echo "NX> 999 Bye"
+	        exit 1
+	fi
+
 else # do not wrap it
 	exec $(dirname $0)/nxssh.orig "$@"
 fi
